# Changes here will be overwritten by Copier
_commit: cdb3937
_src_path: .
copyright_year: '2026'
documentation: false
email: me@cuinixam.com
full_name: cuinixam
github_username: cuinixam
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: false
package_name: poks
project_name: Poks
project_short_description: A lightweight archive downloader for pre-build binary dependencies.
project_slug: poks
run_uv_sync: false
setup_github: false
setup_pre_commit: false

